# R package
# Test an R package

resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: tidyverse

jobs:
  - template: azure-tidyverse.yml@r-azure-pipelines
